# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project\BlenderLauncher\UI\Panel\BlenderLauncher.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BlenderLauncherWindow(object):
    def setupUi(self, BlenderLauncherWindow):
        BlenderLauncherWindow.setObjectName("BlenderLauncherWindow")
        BlenderLauncherWindow.resize(679, 535)
        self.centralwidget = QtWidgets.QWidget(BlenderLauncherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 651, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_ComboBox_WorkSpace_Prefix = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_ComboBox_WorkSpace_Prefix.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_ComboBox_WorkSpace_Prefix.setObjectName("label_ComboBox_WorkSpace_Prefix")
        self.horizontalLayout_3.addWidget(self.label_ComboBox_WorkSpace_Prefix)
        self.comboBox_WorkSpace = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_WorkSpace.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBox_WorkSpace.setEditable(False)
        self.comboBox_WorkSpace.setCurrentText("")
        self.comboBox_WorkSpace.setObjectName("comboBox_WorkSpace")
        self.horizontalLayout_3.addWidget(self.comboBox_WorkSpace)
        self.pushButton_BrowseWorkSpace = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_BrowseWorkSpace.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_BrowseWorkSpace.setMaximumSize(QtCore.QSize(60, 24))
        self.pushButton_BrowseWorkSpace.setObjectName("pushButton_BrowseWorkSpace")
        self.horizontalLayout_3.addWidget(self.pushButton_BrowseWorkSpace)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Render = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Render.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_Render.setObjectName("pushButton_Render")
        self.horizontalLayout.addWidget(self.pushButton_Render)
        self.pushButton_Open = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Open.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.horizontalLayout.addWidget(self.pushButton_Open)
        self.pushButton_Launch = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Launch.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_Launch.setObjectName("pushButton_Launch")
        self.horizontalLayout.addWidget(self.pushButton_Launch)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.listView_WorkSpaceFiles = QtWidgets.QListView(self.gridLayoutWidget)
        self.listView_WorkSpaceFiles.setMaximumSize(QtCore.QSize(16777215, 300))
        self.listView_WorkSpaceFiles.setObjectName("listView_WorkSpaceFiles")
        self.gridLayout.addWidget(self.listView_WorkSpaceFiles, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_ComboBox_Version_Prefix = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_ComboBox_Version_Prefix.setMaximumSize(QtCore.QSize(100, 50))
        self.label_ComboBox_Version_Prefix.setObjectName("label_ComboBox_Version_Prefix")
        self.horizontalLayout_2.addWidget(self.label_ComboBox_Version_Prefix)
        self.comboBox_Version = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_Version.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBox_Version.setMaximumSize(QtCore.QSize(16777215, 24))
        self.comboBox_Version.setObjectName("comboBox_Version")
        self.horizontalLayout_2.addWidget(self.comboBox_Version)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        BlenderLauncherWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BlenderLauncherWindow)
        self.statusbar.setObjectName("statusbar")
        BlenderLauncherWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BlenderLauncherWindow)
        QtCore.QMetaObject.connectSlotsByName(BlenderLauncherWindow)

    def retranslateUi(self, BlenderLauncherWindow):
        _translate = QtCore.QCoreApplication.translate
        BlenderLauncherWindow.setWindowTitle(_translate("BlenderLauncherWindow", "Blender Launcher"))
        self.label_ComboBox_WorkSpace_Prefix.setText(_translate("BlenderLauncherWindow", "WorkSpace"))
        self.pushButton_BrowseWorkSpace.setText(_translate("BlenderLauncherWindow", "Browse"))
        self.pushButton_Render.setText(_translate("BlenderLauncherWindow", "Render"))
        self.pushButton_Open.setText(_translate("BlenderLauncherWindow", "Open"))
        self.pushButton_Launch.setText(_translate("BlenderLauncherWindow", "Launch"))
        self.label_ComboBox_Version_Prefix.setText(_translate("BlenderLauncherWindow", "Version"))
